'use strict';
(() => {
 const F=window.Filament,$=id=>document.getElementById(id),selected=new Set();let items=[];const initialState=new URLSearchParams(location.search).get('state');if(['pending','printed'].includes(initialState))$('printState').value=initialState;
 if(initialState==='pending'){$('pageTitle').textContent='未印刷のQRをまとめて印刷';$('pageIntro').textContent='登録済みで印刷回数0のフィラメントから、今回印刷するものを選びます。'}
 if(initialState==='printed'){$('pageTitle').textContent='QRラベルを再印刷';$('pageIntro').textContent='印刷済みの在庫から、破損・紛失したQRを選んで再印刷します。'}
 const clean=F.clean,field=(row,names)=>{for(const name of names)if(row[name]!=null&&clean(row[name])!=='')return row[name];return ''};
 function number(value){const normalized=clean(value).replaceAll(',','');return normalized===''?null:Number(normalized)}
 function parse(row){const weight=number(field(row,['重量（ｇ）','重量（g）','重量(g)','重量'])),printCount=number(field(row,['印刷回数','QR印刷回数'])),label=clean(field(row,['ラベル注釈','QRラベル注釈']));return {id:clean(field(row,['管理番号(半角)','管理番号（半角）','管理番号'])),maker:clean(row['メーカー']),base:clean(field(row,['母材(ベース)','母材（ベース）','母材'])),sub:clean(row['サブカテゴリ']),color:clean(row['色']),place:clean(row['保管場所']),weight:Number.isFinite(weight)?weight:null,printCount:Number.isFinite(printCount)&&printCount>=0?printCount:null,label,savedLabel:label}}
 function filtered(){const state=$('printState').value;return items.filter(item=>(!$('place').value||item.place===$('place').value)&&(!$('maker').value||item.maker===$('maker').value)&&(state==='all'||(state==='pending'?item.printCount===0:item.printCount!==0))).sort((a,b)=>Number(a.printCount!==0)-Number(b.printCount!==0)||b.id.localeCompare(a.id,'ja'))}
 function updateSelection(){const visible=filtered();$('selectAll').disabled=!visible.length;$('selectAll').checked=visible.length>0&&visible.every(item=>selected.has(item.id));$('selectAll').indeterminate=visible.some(item=>selected.has(item.id))&&!$('selectAll').checked;$('selectedCount').textContent=selected.size+'件選択';$('preview').disabled=!selected.size||selected.size>20;$('selectedIds').replaceChildren();selected.forEach(id=>{const button=document.createElement('button');button.type='button';button.textContent=id+' ×';button.setAttribute('aria-label',id+'の選択を解除');button.onclick=()=>{selected.delete(id);render()};$('selectedIds').append(button)})}
 async function saveLabel(item,button){const value=clean(item.label);button.disabled=true;button.textContent='保存中…';try{const data=await F.updateLabel(item.id,value);item.label=clean(data.label);item.savedLabel=item.label;button.textContent='保存済み';$('status').classList.remove('error');$('status').textContent=item.id+' のラベル注釈を保存しました。'}catch(error){button.disabled=false;button.textContent='注釈を保存';$('status').classList.add('error');$('status').textContent=error.message;return false}return true}
 function render(){const visible=filtered();$('visibleCount').textContent=visible.length+'件表示';$('candidates').replaceChildren();visible.forEach(item=>{const card=document.createElement('div');card.className='candidate'+(selected.has(item.id)?' selected':'');const box=document.createElement('input');box.type='checkbox';box.checked=selected.has(item.id);box.setAttribute('aria-label',item.id+'を選択');box.onchange=()=>{if(box.checked){if(selected.size>=20){box.checked=false;$('status').textContent='一度に選べるのは20件までです。';$('status').classList.add('error');return}selected.add(item.id)}else selected.delete(item.id);render()};const main=document.createElement('span');main.className='candidate-main';const id=document.createElement('span');id.className='candidate-id';id.textContent=item.id;const kind=document.createElement('div');kind.className='candidate-sub';kind.textContent=[item.maker,item.base,item.sub,item.color].filter(Boolean).join(' ／ ');main.append(id,kind);const meta=document.createElement('span');meta.className='candidate-meta';meta.textContent=[item.place,Number(item.weight).toLocaleString('ja-JP')+' g'].join(' ／ ');const count=document.createElement('span');count.className='candidate-print';count.textContent=item.printCount===0?'0回・未印刷':item.printCount==null?'過去データ・印刷済み扱い':item.printCount+'回・印刷操作済';const annotation=document.createElement('div');annotation.className='annotation';const inputLabel=document.createElement('label');inputLabel.textContent='ラベル注釈（60文字まで）';const input=document.createElement('input');input.type='text';input.maxLength=60;input.value=item.label;input.placeholder='例：シルク金、社内呼称など';input.setAttribute('aria-label',item.id+'のラベル注釈');const save=document.createElement('button');save.type='button';save.textContent='注釈を保存';save.disabled=item.label===item.savedLabel;input.oninput=()=>{item.label=input.value;save.disabled=clean(item.label)===item.savedLabel;save.textContent='注釈を保存'};save.onclick=()=>saveLabel(item,save);inputLabel.append(input);annotation.append(inputLabel,save);card.append(box,main,meta,count,annotation);$('candidates').append(card)});updateSelection()}
 async function load(){try{const rows=await F.candidates();items=rows.map(parse).filter(item=>F.validId(item.id)&&item.weight>0);const known=new Set(items.map(item=>item.id));const recent=F.recentRegistrations().filter(item=>!known.has(item.id)&&Number.isFinite(Number(item.weight))&&Number(item.weight)>0);recent.forEach(item=>items.push({id:item.id,maker:clean(item.maker),base:clean(item.base),sub:clean(item.sub),color:clean(item.color),place:clean(item.location),weight:Number(item.weight),printCount:0,label:clean(item.label),savedLabel:clean(item.label),recent:true}));const makers=[...new Set(items.map(item=>item.maker).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'));makers.forEach(maker=>$('maker').add(new Option(maker,maker)));$('maker').disabled=false;$('status').textContent='印刷候補を取得しました。0回は未印刷、空欄の過去データは印刷済みとして扱います。残量0gは除外しています。'+(recent.length?' 登録直後の'+recent.length+'件はCSV反映待ちのため、この端末の登録結果から補完しました。':'');render()}catch(error){$('status').textContent=error.message;$('status').classList.add('error')}}
 for(const id of ['place','maker','printState'])$(id).onchange=render;
 $('selectAll').onchange=()=>{const visible=filtered();if($('selectAll').checked){const available=20-selected.size;visible.filter(item=>!selected.has(item.id)).slice(0,available).forEach(item=>selected.add(item.id));if(visible.some(item=>!selected.has(item.id))){$('status').textContent='最大20件まで選択しました。残りは次の印刷で選んでください。';$('status').classList.add('error')}}else visible.forEach(item=>selected.delete(item.id));render()};
 $('clear').onclick=()=>{selected.clear();render()};
 $('preview').onclick=()=>{const chosen=items.filter(item=>selected.has(item.id));F.localSave('filamentQrAnnotationsV1',Object.fromEntries(chosen.map(item=>[item.id,clean(item.label)])));location.href='./qr.html?ids='+encodeURIComponent(chosen.map(item=>item.id).join('\n'))};
 load();
})();
