'use strict';
(() => {
 const F=window.Filament,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);let busy=false,large=false,printBusy=false,generatedAllIds=[],generatedRegisteredIds=[],generationToken='';const savedNames=F.localLoad('filamentQrAnnotationsV1',{});
 const today=new Date();$('date').value=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
 function status(value,error=false){$('status').textContent=value;$('status').classList.toggle('error',error)}
 function sequenceIds(prefix,date,serial,count){if(!/^20\d{2}-\d{2}-\d{2}$/.test(date)||!Number.isInteger(serial)||!Number.isInteger(count)||serial<1||count<1||count>20||serial+count-1>99)return [];const datePart=date.slice(2).replaceAll('-','');const ids=Array.from({length:count},(_,i)=>prefix+datePart+String(serial+i).padStart(2,'0'));return ids.every(F.validId)?ids:[]}
 function showPlanned(output,label,prefix,date,serial,count){const ids=sequenceIds(prefix,date,serial,count);output.textContent=ids.length?ids.join('\n'):'入力内容を確認してください';label.textContent=count>1?'最初の連番（01〜99）':'入力する連番（01〜99）';return ids}
 function updateMainPlanned(){showPlanned($('plannedIds'),$('serialLabel'),$('prefix').value,$('date').value,$('serial').valueAsNumber,$('count').valueAsNumber)}
 function mode(){const custom=$('mode').value==='custom';$('customFields').hidden=!custom;$('batchFields').hidden=custom;$('ids').required=custom;for(const key of ['date','serial','count'])$(key).disabled=custom;updateMainPlanned()}
 $('mode').onchange=mode;
 const supplied=params.get('ids');if(supplied){$('mode').value='custom';$('ids').value=supplied;status('管理番号を引き継ぎました。内容を確認してQRを作成してください。')}else if(params.get('mode')==='custom'){$('mode').value='custom';status('登録済みの管理番号を入力してください。')}
 $('qrForm').addEventListener('input',()=>{updateMainPlanned();if(!busy){generatedAllIds=[];generatedRegisteredIds=[];generationToken='';$('labels').replaceChildren();$('printTools').hidden=true;$('addPanel').hidden=true;status('条件を変更しました。「登録状況を確認してQRを作る」を押してください。')}});
 function newToken(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():'print-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
 function identifiers(){let ids;if($('mode').value==='custom'){ids=$('ids').value.split(/\r?\n/).map(F.clean).filter(Boolean)}else{ids=sequenceIds($('prefix').value,$('date').value,$('serial').valueAsNumber,$('count').valueAsNumber);if(!ids.length)throw Error('日付・連番・枚数を確認してください。連番は99までです。')}if(!ids.length||ids.length>20)throw Error('管理番号は1〜20件で指定してください。');if(new Set(ids).size!==ids.length)throw Error('同じ管理番号が重複しています。');if(ids.some(id=>!F.validId(id)))throw Error('管理番号はS/O/F＋実在する日付YYMMDD＋連番2桁で入力してください。');return ids}
 function updatePrintAvailability(){const ready=generatedAllIds.length>0&&generatedRegisteredIds.length===generatedAllIds.length;$('print').disabled=!ready;$('print').textContent=ready?'ラベルを印刷':'未登録のIDがあります'}
 function summary(message=''){const registered=generatedRegisteredIds.length,unregistered=generatedAllIds.length-registered;updatePrintAvailability();status((message?message+' ':'')+generatedAllIds.length+'枚を印刷予定。未登録 '+unregistered+'件／登録済み '+registered+'件。'+(unregistered?' 未登録IDを登録すると印刷できます。':''))}
 function rememberLabelNames(){const names={...savedNames};document.querySelectorAll('#labels .qr-label').forEach(card=>{const input=card.querySelector('.label-editor input');if(input)names[card.dataset.id]=F.clean(input.value)});F.localSave('filamentQrAnnotationsV1',names)}
 function label(id,item,name){const box=document.createElement('article');box.className='qr-label';box.dataset.id=id;const qr=new QRious({value:F.itemUrl(id),size:600,level:'M',padding:24});const img=document.createElement('img');img.src=qr.toDataURL();img.alt=id+' のQR';const text=document.createElement('div');text.className='qr-id';text.textContent=id;const n=document.createElement('div');n.className='qr-name';n.textContent=name;const editor=document.createElement('label');editor.className='label-editor no-print';editor.textContent='今回の付与テキスト';const input=document.createElement('input');input.type='text';input.maxLength=60;input.value=name;input.placeholder='空欄でも印刷できます';input.setAttribute('aria-label',id+'の付与テキスト');input.oninput=()=>{n.textContent=input.value};editor.append(input);box.append(img,text,n,editor);const state=document.createElement('p');state.className='qr-state no-print';state.textContent=item?'登録済み・再印刷用':'未登録・登録後に印刷できます';const links=document.createElement('div');links.className='label-links no-print';const open=document.createElement('a');open.className='button primary';open.href=item?'./?id='+encodeURIComponent(id):'./register.html?id='+encodeURIComponent(id);open.textContent=item?'物品情報を開く':'このIDを登録する';if(!item)open.onclick=()=>{rememberLabelNames();const returnIds=generatedAllIds.filter(F.validId);open.href='./register.html?id='+encodeURIComponent(id)+'&returnIds='+encodeURIComponent(returnIds.join('\n'))};const download=document.createElement('a');download.className='button';download.href=img.src;download.download=id+'.png';download.textContent='QR画像を保存';const remove=document.createElement('button');remove.type='button';remove.textContent='このQRを外す';remove.onclick=()=>{box.remove();generatedAllIds=generatedAllIds.filter(value=>value!==id);generatedRegisteredIds=generatedRegisteredIds.filter(value=>value!==id);generationToken=generatedAllIds.length?newToken():'';$('printTools').hidden=!generatedAllIds.length;$('addPanel').hidden=true;summary('QRを外しました。')};links.append(open,download,remove);box.append(state,links);return box}
 $('qrForm').onsubmit=async event=>{event.preventDefault();if(busy||!$('qrForm').reportValidity())return;let ids;try{ids=identifiers();if(typeof QRious==='undefined')throw Error('QR作成機能を取得できません。ページを再読込してください。')}catch(error){status(error.message,true);return}busy=true;$('qrFields').disabled=true;$('printTools').hidden=true;$('addPanel').hidden=true;$('labels').replaceChildren();const name=F.clean($('labelName').value);try{const items=[];for(let i=0;i<ids.length;i++){status('登録状況を確認しています… '+(i+1)+' / '+ids.length);items.push(await F.lookup(ids[i]))}const fragment=document.createDocumentFragment();ids.forEach((id,i)=>fragment.append(label(id,items[i],Object.hasOwn(savedNames,id)?F.clean(savedNames[id]):name)));$('labels').append(fragment);generatedAllIds=ids.slice();generatedRegisteredIds=ids.filter((id,i)=>Boolean(items[i]));generationToken=newToken();$('printTools').hidden=false;summary('QRを作成しました。')}catch(error){generatedAllIds=[];generatedRegisteredIds=[];generationToken='';$('labels').replaceChildren();status('QRは作成していません。'+error.message,true)}finally{busy=false;$('qrFields').disabled=false;mode()}};
 function addMode(){const custom=$('addMethod').value==='custom';$('addNextFields').hidden=custom;$('addCustomFields').hidden=!custom;updateAddPlanned()}
 function updateAddPlanned(){showPlanned($('addPlannedIds'),$('addSerialLabel'),$('addPrefix').value,$('addDate').value,$('addSerial').valueAsNumber,$('addCount').valueAsNumber)}
 function prepareAdd(){const last=generatedAllIds.at(-1);if(last&&F.validId(last)){$('addPrefix').value=last[0];$('addDate').value='20'+last.slice(1,3)+'-'+last.slice(3,5)+'-'+last.slice(5,7);$('addSerial').value=String(Math.min(99,Number(last.slice(-2))+1))}else{$('addPrefix').value=$('prefix').value;$('addDate').value=$('date').value;$('addSerial').value='1'}$('addCount').value='1';$('addLabelName').value='';$('addMethod').value='next';$('addIds').value='';addMode();$('addPanel').hidden=false;$('addSerial').focus()}
 $('addQr').onclick=prepareAdd;$('addCancel').onclick=()=>{$('addPanel').hidden=true;$('addIds').value=''};$('addMethod').onchange=addMode;for(const key of ['addPrefix','addDate','addSerial','addCount'])$(key).oninput=updateAddPlanned;
 $('addConfirm').onclick=async()=>{if(busy)return;const ids=$('addMethod').value==='custom'?$('addIds').value.split(/\r?\n/).map(value=>F.clean(value).toUpperCase()).filter(Boolean):sequenceIds($('addPrefix').value,$('addDate').value,$('addSerial').valueAsNumber,$('addCount').valueAsNumber);if(!ids.length||ids.some(id=>!F.validId(id))){status('追加する日付・連番・枚数を確認してください。',true);return}if(new Set(ids).size!==ids.length||ids.some(id=>generatedAllIds.includes(id))){status('同じ管理番号が印刷リストに含まれています。',true);return}if(generatedAllIds.length+ids.length>20){status('印刷リストは合計20枚までです。',true);return}busy=true;$('addConfirm').disabled=true;try{const items=[];for(let i=0;i<ids.length;i++){status('追加する管理番号を確認しています… '+(i+1)+' / '+ids.length);items.push(await F.lookup(ids[i]))}const fragment=document.createDocumentFragment(),name=F.clean($('addLabelName').value);ids.forEach((id,i)=>fragment.append(label(id,items[i],Object.hasOwn(savedNames,id)?F.clean(savedNames[id]):name)));$('labels').append(fragment);generatedAllIds.push(...ids);generatedRegisteredIds.push(...ids.filter((id,i)=>Boolean(items[i])));generationToken=newToken();$('addPanel').hidden=true;$('addIds').value='';summary('QRを追加しました。')}catch(error){status('QRを追加できませんでした。'+error.message,true)}finally{busy=false;$('addConfirm').disabled=false}};
 $('print').onclick=async()=>{if(printBusy||!generationToken)return;if(generatedRegisteredIds.length!==generatedAllIds.length){summary('未登録IDが残っているため印刷できません。');return}printBusy=true;$('print').disabled=true;status('印刷回数の記録準備をしています…');try{const healthUrl=new URL(F.api);healthUrl.searchParams.set('action','health');const health=await F.request(healthUrl);if(!health.ok||!health.actions?.includes('markPrinted')){status('公開中のGASは印刷回数の記録に未対応です。今回は回数を記録せず印刷します。',true);window.print();return}const result=await F.request(F.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({action:'markPrinted',ids:generatedRegisteredIds,token:generationToken})});if(!result.ok||result.action!=='markPrinted'||result.token!==generationToken)throw Error(result.message||result.error||'印刷回数の更新結果を確認できませんでした。');status(result.duplicate?'同じQR生成のため印刷回数は追加せず、印刷画面を開きます。':generatedRegisteredIds.length+'件の印刷回数を1加算しました。');window.print()}catch(error){status(error.message||'印刷回数を更新できませんでした。',true)}finally{printBusy=false;updatePrintAvailability()}};
 $('size').onclick=()=>{large=!large;$('labels').classList.toggle('large',large);$('size').textContent=large?'縮小（3cm）':'拡大（5cm）';$('size').setAttribute('aria-pressed',String(large))};mode();addMode();if(supplied)$('qrForm').requestSubmit();
})();
