'use strict';
(() => {
 const F=window.Filament,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
 const firstId=F.clean(params.get('id')),requested=Number(params.get('count')||1),firstSerial=Number(firstId.slice(-2));
 const returnIds=(params.get('returnIds')||'').split(/\r?\n/).map(F.clean).filter(F.validId).slice(0,20);
 const count=Number.isInteger(requested)&&requested>=1&&requested<=20?requested:0;
 const ids=count&&F.validId(firstId)&&firstSerial+count-1<=99?Array.from({length:count},(_,i)=>firstId.slice(0,-2)+String(firstSerial+i).padStart(2,'0')):[];
 const definitions=[['maker','メーカー','メーカー'],['base','素材','母材(ベース)'],['color','色','色'],['sub','サブカテゴリ','サブカテゴリ'],['person','今回の担当','担当']];
 const defaults={maker:['CC3D','kexcelled','bambu','OVERTURE','ノーブランド'],base:['PLA','PLA＋','ABS','PETG','ASA','TPU'],color:['赤','黒','白','青','灰色','緑','ナチュラル'],sub:['標準','silk','wood','carbon','サポート用'],person:[]};
 let dataRows=[],masterItems=[],mastersReady=false,busy=false,unknown=false,exists=false,refreshing=false,loadingCandidates=true;
 const pending=F.localLoad('filamentRegistrationPendingV1',{}),pendingAny=()=>ids.some(id=>Boolean(pending[id]));
 function status(value,error=false){$('status').textContent=value;$('status').classList.toggle('error',error)}
 function value(key){return $(key).value==='__custom__'?F.clean($(key+'Custom').value):F.clean($(key).value)}
 function control(){$('fields').disabled=busy||refreshing||loadingCandidates||!mastersReady||!unknown||pendingAny();$('retry').disabled=$('check').disabled=$('acknowledge').disabled=busy||refreshing;$('uncertain').hidden=!pendingAny();$('acknowledge').hidden=exists}
 function fill(key,values){const selected=$(key).value,select=$(key);select.replaceChildren(new Option('選択してください',''));[...new Set(values.map(F.clean).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja')).forEach(v=>select.add(new Option(v,v)));if(selected&&selected!=='__custom__'&&!values.includes(selected))select.add(new Option(selected,selected));select.add(new Option('候補にない名前を入力','__custom__'));select.value=selected}
 function applyMaster(){const item=masterItems.find(item=>item.id===$('filamentKey').value);for(const key of ['maker','base','color','sub']){const select=$(key),customBox=$(key+'Box');const text=item?F.clean(item[key]):'';select.replaceChildren(new Option(text||'フィラメントを選択してください',text));select.value=text;customBox.hidden=true;$(key+'Custom').required=false}$('candidateStatus').textContent=item?[item.maker,item.product,item.base,item.sub,item.color].filter(Boolean).join(' ／ '):'フィラメントマスターから選択してください。'}
 for(const [key,label] of definitions){const box=document.createElement('div'),lab=document.createElement('label'),select=document.createElement('select'),customLabel=document.createElement('label'),custom=document.createElement('input'),customBox=document.createElement('div');lab.className='field';lab.htmlFor=key;lab.textContent=label+'（必須）';select.id=key;select.required=true;customLabel.className='field';customLabel.htmlFor=key+'Custom';customLabel.textContent=label+'を入力';custom.id=key+'Custom';custom.maxLength=100;customBox.id=key+'Box';customBox.hidden=true;customBox.append(customLabel,custom);box.append(lab,select,customBox);$('choices').append(box);fill(key,defaults[key]);if(key==='person'){select.onchange=()=>{customBox.hidden=select.value!=='__custom__';custom.required=!customBox.hidden}}else select.disabled=true}
 function detail(values){$('detail').replaceChildren();for(const [label,text] of values){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=String(text??'—');$('detail').append(dt,dd)}}
 function showExisting(item,title,targetId=firstId){exists=true;unknown=false;$('entry').hidden=true;$('existing').hidden=false;$('existingTitle').textContent=title;detail([['管理番号',targetId],['メーカー',item.maker],['素材',item.base],['色',item.color],['保管場所',item.location],['重量（g）',item.weight],['担当',item.person]]);$('openItem').hidden=false;$('openItem').href='./?id='+encodeURIComponent(targetId);$('openItem').textContent='登録したフィラメントの情報を開く';const backIds=returnIds.length?returnIds:[targetId];$('createQr').href='./qr.html?ids='+encodeURIComponent(backIds.join('\n'));$('createQr').textContent=returnIds.length?'印刷予定へ戻る':'今すぐこのIDのQRを作成する';control()}
 function showBatchComplete(base,completed=ids,title=count+'本の登録が完了しました'){exists=true;unknown=false;$('entry').hidden=true;$('existing').hidden=false;$('existingTitle').textContent=title;detail([['管理番号',completed.length===1?completed[0]:completed[0]+' ～ '+completed.at(-1)],['本数',completed.length+'本'],['メーカー',base.maker],['素材',base.base],['色',base.color],['保管場所',base.location],['重量',base.weight+'g／本'],['担当',base.person]]);$('openItem').hidden=true;$('createQr').href='./qr.html?ids='+encodeURIComponent(completed.join('\n'));$('createQr').textContent='今すぐ'+completed.length+'本のQRを作成する';control()}
 async function check(){if(busy||refreshing||!ids.length)return;refreshing=true;unknown=false;exists=false;$('retry').hidden=true;$('entry').hidden=true;$('existing').hidden=true;control();status('登録状況を確認しています…');try{const found=[];for(const targetId of ids){const item=await F.lookup(targetId);if(item)found.push({id:targetId,item})}if(found.length){if(found.length===ids.length&&ids.length>1){showBatchComplete(found[0].item,ids,ids.length+'本とも登録済みです');status('上書きはしません。')}else{showExisting(found[0].item,ids.length>1?'一括登録を開始できません':'登録済みのフィラメント',found[0].id);status(ids.length>1?found.length+'本がすでに登録済みです。重複を避けるため一括登録を開始していません。':pendingAny()?'台帳への登録を確認できました。履歴の完了状態も確認してください。':'登録済みです。上書きはしません。',ids.length>1)}return}unknown=true;$('entry').hidden=false;status(pendingAny()?'処理結果が不明な管理番号があります。履歴を確認してください。':ids.length>1?ids[0]+' ～ '+ids.at(-1)+' の '+ids.length+'本は未登録です。共通情報を入力してください。':'未登録です。内容を入力してください。')}catch(error){status(error.message,true);$('retry').hidden=false}finally{refreshing=false;control()}}
 async function loadCandidates(){try{masterItems=await F.filamentMasters();const select=$('filamentKey');select.replaceChildren(new Option('選択してください',''));masterItems.sort((a,b)=>[a.maker,a.base,a.sub,a.color].join('\u001f').localeCompare([b.maker,b.base,b.sub,b.color].join('\u001f'),'ja')).forEach(item=>{const label=[item.maker,item.product,item.base,item.sub,item.color].filter(Boolean).join(' ／ ');select.add(new Option(label,item.id))});mastersReady=masterItems.length>0;if(!mastersReady)throw Error('フィラメントマスターが空です。');try{dataRows=await F.candidates()}catch{dataRows=[]}fill('person',[...dataRows.map(r=>r['担当']),...defaults.person]);const person=F.localLoad('filamentPersonV1','');if(person){fill('person',[...dataRows.map(r=>r['担当']),person]);$('person').value=person}$('candidateStatus').textContent='フィラメントマスターから商品を選択してください。'}catch(error){mastersReady=false;$('filamentKey').replaceChildren(new Option('取得できませんでした',''));$('candidateStatus').textContent=error.message}finally{loadingCandidates=false;control()}}
 $('filamentKey').onchange=applyMaster;
 $('form').onsubmit=async event=>{event.preventDefault();if(busy||refreshing||!unknown||pendingAny()||!$('form').reportValidity())return;const base={action:'register',filamentKey:$('filamentKey').value,location:$('location').value,weight:$('weight').valueAsNumber,note:F.clean($('note').value)};definitions.forEach(([key])=>base[key]=value(key));if(!/^FL\d{6}$/.test(base.filamentKey)||definitions.some(([key])=>!base[key])||!base.note||!Number.isFinite(base.weight)||base.weight<0||base.weight>5000){status('フィラメント、必須項目、重量を確認してください。',true);return}busy=true;control();const completed=[];let currentId='';status('登録先と管理番号を確認しています…');try{await F.verify();for(const targetId of ids){if(await F.lookup(targetId))throw Error(targetId+' は別の操作で登録済みになりました。一括登録を開始していません。')}for(let i=0;i<ids.length;i++){currentId=ids[i];const payload={...base,id:currentId};pending[currentId]={at:new Date().toISOString()};F.localSave('filamentRegistrationPendingV1',pending);control();status((i+1)+'/'+ids.length+'本目（'+currentId+'）を登録しています…');const result=await F.request(F.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});if(!result.ok){if(result.error!=='UPDATE_REQUIRES_REVIEW'){delete pending[currentId];F.localSave('filamentRegistrationPendingV1',pending)}throw Error(result.message||result.error||currentId+'を登録できませんでした。')}if(result.id!==currentId||result.action!=='register'||result.apiVersion!=='filament-form-history-v3'||result.historyStatus!=='完了'||result.historySheet!=='フォームの回答 1'||!result.operationId)throw Error(currentId+'の登録と履歴保存の結果を確認できませんでした。');delete pending[currentId];F.localSave('filamentRegistrationPendingV1',pending);F.rememberRegistration(payload);completed.push(currentId)}F.localSave('filamentPersonV1',base.person);if(ids.length>1)showBatchComplete(base);else showExisting({...base,id:firstId},'登録が完了しました。',firstId);status('在庫台帳と「フォームの回答 1」に、'+ids.length+'本を1行ずつ記録しました。')}catch(error){if(completed.length){showBatchComplete(base,completed,completed.length+'本は登録完了／残りは停止しました');status(completed.length+'本は登録済みです。重複を避けるため自動再送していません。\n'+error.message,true)}else status(currentId&&pending[currentId]?'結果を確認できません。登録済みの可能性があるため、自動再送はしていません。\n'+error.message:error.message,true)}finally{busy=false;control()}};
 $('check').onclick=$('retry').onclick=check;$('acknowledge').onclick=()=>{if(busy||refreshing||exists)return;ids.forEach(targetId=>delete pending[targetId]);F.localSave('filamentRegistrationPendingV1',pending);check()};
 if(!firstId){location.replace('./register-start.html');return}
 if(!ids.length){status('管理番号または本数を確認してください。1回に登録できるのは20本まで、連番は99までです。',true);$('retry').hidden=true;$('entry').hidden=true;return}
 $('id').value=ids.length===1?firstId:firstId+' ～ '+ids.at(-1)+'（'+ids.length+'本）';$('intro').textContent=ids.length===1?'管理番号を確認して、フィラメントを1本登録します。':'共通情報を一度入力し、'+ids.length+'本を連番で登録します。';$('submit').textContent=ids.length===1?'この内容で登録する':ids.length+'本をこの内容で一括登録する';$('location').value=F.places[firstId[0]];loadCandidates();check();
})();
